### ISSUE TITLE
Drag Drop

### ISSUE THREAD

**Issue by limelect** [federgraph/federgraph-meme-builder#1]
D10.2.3
Drag Drop does not work

**Comment by federgraph** [comment]
D10.3.3
Seems to work for me on Windows. I just tested with png and jpg image files.

**Comment by limelect** [comment]
Can you add a load file button?

**Comment by limelect** [comment]
Can you add a load file button?

**Comment by federgraph** [comment]
Can you not do this yourself? OnDropTargetDropped takes a fileName, just pass the file name from some OpenFileDialog, if available on the platform. The DropTarget works for me when I compile with 10.2.3, Win32 target. What target platform are we talking about?

**Comment by limelect** [comment]
I will thanks
